---
- hosts: localhost
  connection: local
  tasks:

   - name: launching aws
     amazon.aws.ec2_instance:
       name: "public-compute-instance"
       image_id: "ami-07ac0a74d21a3174c"
       security_group: MOS-Flight-SG-DC-VPN-CMB-Office-20230119100213514800000001
       key_name: "sanjaya"
       region: ap-southeast-1
       vpc_subnet_id: subnet-024c6a259a7627076
       count: 1
       instance_type: t2.micro
       wait: yes
       user_data: "{{ lookup('file', 'ec2') }}"
     register: ec2

   
    
   
